Get http://localhost:5128/api/stock/1



###
POST http://localhost:5128/api/stock/
Content-Type: application/json

{
                "Symbol" : "New1",
                "CompanyName" : "newt234ng",
                "Purchase" : 1431,
                "LastDiv" : 5,
                "Industry" : "any",
                "MarketCap" : 1028
}

###
PUT http://localhost:5128/api/stock/3
Content-Type: application/json

{
                "Symbol" : "hello",
                "CompanyName" : "newtesting111",
                "Purchase" : 101,
                "LastDiv" : 1,
                "Industry" : "any",
                "MarketCap" : 10291381
}

###
POST http://localhost:5128/api/Comment/2
Content-Type: application/json

{
                "Title" : "jkjjk",
                "Content" : "qwiiinqrasd sdsdifn asdifnsd fsnfsd afnas fasjnfasdnf asdfnas fasdnfasd foasdnf"

             
}

###
PUT http://localhost:5128/api/Comment/4
Content-Type: application/json

{
                "Title" : "abcd",
                "Content" : "abcde",
                "StockId" : 1
             
}
